# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 240)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/qr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_texto = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_texto.setGeometry(QtCore.QRect(12, 50, 291, 20))
        self.lineEdit_texto.setObjectName("lineEdit_texto")
        self.pushButton_aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_aceptar.setGeometry(QtCore.QRect(20, 160, 75, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/aceptar/aceptar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_aceptar.setIcon(icon1)
        self.pushButton_aceptar.setObjectName("pushButton_aceptar")
        self.pushButton_salir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_salir.setGeometry(QtCore.QRect(230, 160, 75, 23))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/salir/salir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_salir.setIcon(icon2)
        self.pushButton_salir.setObjectName("pushButton_salir")
        self.pushButton_limpiar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_limpiar.setGeometry(QtCore.QRect(230, 80, 75, 23))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/limpiar/limpiar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_limpiar.setIcon(icon3)
        self.pushButton_limpiar.setObjectName("pushButton_limpiar")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(10, 10, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_titulo.setFont(font)
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 120, 300, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.labelstatusbar = QtWidgets.QLabel(self.centralwidget)
        self.labelstatusbar.setGeometry(QtCore.QRect(120, 160, 47, 13))
        self.labelstatusbar.setText("")
        self.labelstatusbar.setObjectName("labelstatusbar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GeneradorQR"))
        self.lineEdit_texto.setToolTip(_translate("MainWindow", "Introduzca el texto..."))
        self.lineEdit_texto.setPlaceholderText(_translate("MainWindow", "Introduzca el texto..."))
        self.pushButton_aceptar.setToolTip(_translate("MainWindow", "Aceptar"))
        self.pushButton_aceptar.setText(_translate("MainWindow", "Aceptar"))
        self.pushButton_salir.setToolTip(_translate("MainWindow", "Salir"))
        self.pushButton_salir.setText(_translate("MainWindow", "Salir"))
        self.pushButton_limpiar.setToolTip(_translate("MainWindow", "Limpiar"))
        self.pushButton_limpiar.setText(_translate("MainWindow", "Limpiar"))
        self.label_titulo.setText(_translate("MainWindow", "GENERADOR DE CODIGOS QR"))
import aceptar_rc
import icon_rc
import limpiar_rc
import salir_rc
